public class ArCalculations {
    public void addition(Integer a,Integer b) {
Integer z=a+b;
System.debug('Total is '+z);
    }
    public void subtraction(Integer a,Integer b){
        Integer z=a-b;
        System.debug('Result is '+z);
    }
    public void multiplication(Integer a,Integer b){
        Integer z=a*b;
        system.debug('Result is '+z);
    }
    public void division(Integer a,Integer b){
        Integer z=a/b;
        System.debug('result '+z);
    }
}