public class calNew {
    public string printReturnMethods(String text) {
String fullText=text+ ' We are in the vacation!';
return fullText;
    }
    public boolean leapyear(integer dt){
        
        boolean lp=date.isLeapYear(dt);
        return lp;
    }
    public integer addition(Integer a,Integer b){
        return a+b;
    }
    public integer addition(Integer a,Integer v,Integer j){
        return a+v+j;
    }
    
    
}