public class listSetMapPracticeExtra {
    // public static List <string> toCaps(List<String> lst){
    // List<String> myList=new List<String>();
    // for (String eachElement : lst) {
    //     mylist.add(eachElement.capitalize());
    // }
    // return myList;
    // }
    // public static void printTheAge(List<Date> dts){
    //     date todaysdate=date.today();
    //     for ( Date eachdd : dts) {
    //         system.debug(eachdd);
    //         Integer days=eachdd.daysBetween(todaysdate);
    //         Integer age=Integer.valueOf(days/365);
    //         system.debug(age);
    //     }
    // }
    
}