public class MethodPractice {
    public void MethodBoolean() {
Boolean myVar=True;
System.debug(myVar);
    }
    public void MethodInteger(){
        Integer varFirst=1;
        Integer varSecond=2;
        system.debug(varFirst+' is First Variable');
        system.debug(varSecond+' is Second Variable.');
    }
    public void MethodString(){
        String varName1='Name';
        String varName2='Your Name';
        System.debug(varName1+' '+varName2);
    }
}