// classwork1 demo=new classwork1();
// demo.printsubscription();
// demo.welcomeMSG('Welcome home');
//calNew printme=new calNew();
// String p=printme.printReturnMethods('Here we go');
// system.debug(p);
// Boolean b=printme.leapyear(2024);
// system.debug(b);
// Integer result=printme.addition(6,6);
// system.debug(result);
// Integer sum=printme.addition(9,9,9);
// system.debug(sum);
// Date nu=date.today();
//
// system.debug(n);